// Entry codes — a strictly 10-digit unique code auto-assigned to every
// APPROVED competition entry — over real HTTP against real PostgreSQL.
//
// The code is generated by a database TRIGGER, not application code, because
// there are three separate places in this codebase that can approve an entry
// (the admin queue, the Top 10 entries editor, and admin-added entries that
// are inserted already-approved). A trigger is the one mechanism that cannot
// be forgotten by a fourth call site added later — which is exactly the kind
// of thing that can't be proven by reading the code, only by exercising it
// against a real database.
//
// Run with:  npm test   (from unplug-backend/)

const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const EmbeddedPostgres = require('embedded-postgres').default;

let pg;
let pool;
let server;
let baseUrl;
let adminToken;
let memberToken;
const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'unplug-entrycodes-'));
const port = 9000 + (process.pid % 300); // unique per test file: bases are 400 apart so the offset ranges cannot overlap

function migrationFiles() {
  const dir = path.join(__dirname, '..', 'db', 'migrations');
  return fs.readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()
    .map((f) => path.join(dir, f));
}
async function runMigrations() {
  for (const file of migrationFiles()) {
    await pool.query(fs.readFileSync(file, 'utf8'));
  }
}

async function req(method, urlPath, { token, body } = {}) {
  const res = await fetch(baseUrl + urlPath, {
    method,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  let json = null;
  try { json = await res.json(); } catch (e) { /* no body */ }
  return { status: res.status, body: json };
}

before(async () => {
  pg = new EmbeddedPostgres({
    databaseDir: dataDir, user: 'postgres', password: 'postgres', port,
    persistent: false, initdbFlags: ['--encoding=UTF8', '--locale=C'],
  });
  await pg.initialise();
  await pg.start();
  await pg.createDatabase('unplug_test');

  process.env.DATABASE_URL = `postgres://postgres:postgres@localhost:${port}/unplug_test`;
  process.env.JWT_SECRET = 'test-secret-for-entry-codes';

  const { Pool } = require('pg');
  pool = new Pool({ connectionString: process.env.DATABASE_URL });
  await runMigrations();

  const jwt = require('jsonwebtoken');
  await pool.query(`INSERT INTO users (id, email, password_hash, role)
                    VALUES (1, 'admin@test.com', 'x', 'admin'),
                           (2, 'member@test.com', 'x', 'member')
                    ON CONFLICT DO NOTHING`);
  adminToken = jwt.sign({ id: 1, email: 'admin@test.com', role: 'admin' }, process.env.JWT_SECRET);
  memberToken = jwt.sign({ id: 2, email: 'member@test.com', role: 'member' }, process.env.JWT_SECRET);

  const express = require('express');
  const { attachUser } = require('../src/middleware/auth');
  const app = express();
  app.use(express.json());
  app.use(attachUser);
  app.use('/', require('../src/routes/competitions'));
  app.use((err, _req, res, _next) => res.status(500).json({ error: err.message }));
  await new Promise((resolve) => { server = app.listen(0, resolve); });
  baseUrl = `http://127.0.0.1:${server.address().port}`;
}, { timeout: 120000 });

after(async () => {
  if (server) await new Promise((r) => server.close(r));
  if (pool) await pool.end();
  // Windows can still hold a handle on the data directory when Postgres
  // exits, and embedded-postgres removes that directory as part of
  // stopping. The server is already down by then, so an EBUSY here is
  // the OS being slow to let go, not a failure worth failing the file
  // for — and a teardown that goes red teaches everyone to ignore red.
  try { if (pg) await pg.stop(); } catch (e) { /* see above */ }
  fs.rmSync(dataDir, { recursive: true, force: true });
});

// profiles.user_id is UNIQUE — one profile per account — so each call needs
// its OWN user, not a shared id reused across entries. Auto-incrementing from
// a high base keeps every call's user id distinct within this file.
let _nextTestUserId = 1000;
async function makeProfile(slug) {
  const userId = _nextTestUserId++;
  await pool.query(`INSERT INTO users (id, email, password_hash, role)
                    VALUES ($1, $2, 'x', 'member') ON CONFLICT DO NOTHING`, [userId, `${slug}@test.com`]);
  await pool.query(`INSERT INTO profiles (user_id, display_name, slug, package_tier)
                    VALUES ($1, $2, $3, 'basic') ON CONFLICT DO NOTHING`, [userId, slug, slug]);
  const r = await pool.query('SELECT id FROM profiles WHERE slug = $1', [slug]);
  return r.rows[0].id;
}

// -------------------------------------------------------------------- path 1
// Admin-added entry: INSERT already 'approved' — no separate UPDATE happens.

test('an admin-added manual entry gets a code immediately, in the API response', async () => {
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'top-10'`);
  const r = await req('POST', `/competitions/${comp.rows[0].id}/admin-entries`, {
    token: adminToken, body: { manualName: 'Instant Approve' },
  });
  assert.equal(r.status, 201);
  assert.equal(r.body.entry.status, 'approved');
  assert.match(r.body.entry.entry_code, /^[0-9]{10}$/, `expected a 10-digit code, got "${r.body.entry.entry_code}"`);
});

// -------------------------------------------------------------------- path 2
// PATCH /admin/entries/:id/approve — this test file only mounts competitions.js
// (admin.js has its own heavier test suite), so this exercises the same UPDATE
// the trigger must fire on directly, proving the trigger — not admin.js's
// route handler — is what assigns the code.

test('approving a pending entry (UPDATE, not INSERT) assigns a code that was NULL before', async () => {
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'the-arena'`);
  const profileId = await makeProfile('pending-entrant');
  const inserted = await pool.query(
    `INSERT INTO competition_entries (competition_id, profile_id, entry_fee, status)
     VALUES ($1, $2, 0, 'pending') RETURNING id`,
    [comp.rows[0].id, profileId]
  );
  const id = inserted.rows[0].id;

  const before = await pool.query('SELECT entry_code FROM competition_entries WHERE id = $1', [id]);
  assert.equal(before.rows[0].entry_code, null, 'a pending entry should not have a code yet');

  await pool.query(`UPDATE competition_entries SET status = 'approved' WHERE id = $1`, [id]);
  const after = await pool.query('SELECT entry_code FROM competition_entries WHERE id = $1', [id]);
  assert.match(after.rows[0].entry_code, /^[0-9]{10}$/);
});

test('rejecting an entry never assigns a code', async () => {
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'the-arena'`);
  const profileId = await makeProfile('rejected-entrant');
  const inserted = await pool.query(
    `INSERT INTO competition_entries (competition_id, profile_id, entry_fee, status)
     VALUES ($1, $2, 0, 'pending') RETURNING id`,
    [comp.rows[0].id, profileId]
  );
  await pool.query(`UPDATE competition_entries SET status = 'rejected' WHERE id = $1`, [inserted.rows[0].id]);
  const row = await pool.query('SELECT entry_code FROM competition_entries WHERE id = $1', [inserted.rows[0].id]);
  assert.equal(row.rows[0].entry_code, null);
});

// -------------------------------------------------------------------- backfill

test('an entry approved BEFORE this migration existed gets backfilled a code', async () => {
  // Simulates real production data: a row that was already 'approved' before
  // migration 070's trigger existed. The trigger is always active once it
  // exists, so a plain INSERT (or an UPDATE afterwards, like setting
  // entry_code back to NULL) would just have the trigger fill it straight
  // back in on the spot — which is correct behaviour, but means it's
  // impossible to simulate "old data with no code yet" without briefly
  // disabling the trigger for one write, exactly as it would never have run
  // for a row inserted before the trigger was created.
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'the-arena'`);
  const profileId = await makeProfile('legacy-entrant');
  await pool.query('ALTER TABLE competition_entries DISABLE TRIGGER trg_assign_entry_code');
  await pool.query(
    `INSERT INTO competition_entries (competition_id, profile_id, entry_fee, status)
     VALUES ($1, $2, 0, 'approved')`,
    [comp.rows[0].id, profileId]
  );
  await pool.query('ALTER TABLE competition_entries ENABLE TRIGGER trg_assign_entry_code');

  const before = await pool.query('SELECT entry_code FROM competition_entries WHERE profile_id = $1', [profileId]);
  assert.equal(before.rows[0].entry_code, null);

  await runMigrations();

  const after = await pool.query('SELECT entry_code FROM competition_entries WHERE profile_id = $1', [profileId]);
  assert.match(after.rows[0].entry_code, /^[0-9]{10}$/, 'the backfill did not assign a code on re-run');
});

test('re-running migrations does NOT change a code an entry already has', async () => {
  const before = await pool.query(`SELECT id, entry_code FROM competition_entries WHERE entry_code IS NOT NULL LIMIT 1`);
  const { id, entry_code } = before.rows[0];
  await runMigrations();
  const after = await pool.query('SELECT entry_code FROM competition_entries WHERE id = $1', [id]);
  assert.equal(after.rows[0].entry_code, entry_code, 'a stable code was regenerated by re-running migrations');
});

// ------------------------------------------------------------------ format

test('codes are exactly 10 digits and unique across every approved entry', async () => {
  const rows = await pool.query(`SELECT entry_code FROM competition_entries WHERE entry_code IS NOT NULL`);
  assert.ok(rows.rowCount >= 3, 'expected several codes to have been generated by earlier tests');
  const seen = new Set();
  for (const r of rows.rows) {
    assert.match(r.entry_code, /^[0-9]{10}$/, `"${r.entry_code}" is not exactly 10 digits`);
    assert.ok(!seen.has(r.entry_code), `duplicate code ${r.entry_code}`);
    seen.add(r.entry_code);
  }
});

test('the database itself refuses a duplicate code — the real guarantee, not just the generator', async () => {
  const existing = await pool.query(`SELECT entry_code FROM competition_entries WHERE entry_code IS NOT NULL LIMIT 1`);
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'the-arena'`);
  const profileId = await makeProfile('duplicate-code-attempt');
  await assert.rejects(
    pool.query(
      `INSERT INTO competition_entries (competition_id, profile_id, entry_fee, status, entry_code)
       VALUES ($1, $2, 0, 'approved', $3)`,
      [comp.rows[0].id, profileId, existing.rows[0].entry_code]
    ),
    /unique|duplicate/i,
    'the unique index did not reject a duplicate entry_code'
  );
});

// ---------------------------------------------------------------- lookups

test('GET /entries/:id resolves an approved entry', async () => {
  const row = await pool.query(`SELECT id, entry_code FROM competition_entries WHERE status = 'approved' LIMIT 1`);
  const r = await req('GET', `/entries/${row.rows[0].id}`);
  assert.equal(r.status, 200);
  assert.equal(r.body.entry.entry_code, row.rows[0].entry_code);
});

test('GET /entries/:id 404s for a pending entry — the code exists to find PUBLIC entries only', async () => {
  // A fresh entry, not a leftover from an earlier test — every earlier
  // 'pending' fixture in this file has since been approved or rejected, so
  // relying on one still being pending here would be fragile against test
  // order and against future tests being added.
  const comp = await pool.query(`SELECT id FROM competitions WHERE slug = 'the-arena'`);
  const profileId = await makeProfile('still-pending-entrant');
  const inserted = await pool.query(
    `INSERT INTO competition_entries (competition_id, profile_id, entry_fee, status)
     VALUES ($1, $2, 0, 'pending') RETURNING id`,
    [comp.rows[0].id, profileId]
  );
  const r = await req('GET', `/entries/${inserted.rows[0].id}`);
  assert.equal(r.status, 404);
});

test('GET /entries/by-code/:code resolves the right entry', async () => {
  const row = await pool.query(`SELECT id, entry_code FROM competition_entries WHERE status = 'approved' LIMIT 1`);
  const r = await req('GET', `/entries/by-code/${row.rows[0].entry_code}`);
  assert.equal(r.status, 200);
  assert.equal(r.body.entry.id, row.rows[0].id);
});

test('GET /entries/by-code/:code is NOT swallowed by the GET /entries/:id route', async () => {
  // Regression guard for the exact ordering bug this route pairing invites:
  // if /entries/:id were registered first, this request would match it with
  // id="by-code" and fail with "a valid entry id is required" instead of ever
  // reaching the code lookup.
  const row = await pool.query(`SELECT entry_code FROM competition_entries WHERE status = 'approved' LIMIT 1`);
  const r = await req('GET', `/entries/by-code/${row.rows[0].entry_code}`);
  assert.notEqual(r.body && r.body.error, 'A valid entry id is required.');
  assert.equal(r.status, 200);
});

test('a malformed code is refused with a clear message, not a database error', async () => {
  const r = await req('GET', '/entries/by-code/not-ten-digits');
  assert.equal(r.status, 400);
});

test('an unknown code returns 404, not an empty success', async () => {
  const r = await req('GET', '/entries/by-code/0000000000');
  assert.equal(r.status, 404);
});
