// Dumping the database without pg_dump.
//
// WHY NOT pg_dump. It is not there. Render's Node runtime does not include the
// PostgreSQL client tools, and the embedded-postgres package used in tests
// ships only initdb and postgres — no pg_dump, no pg_restore, no psql. A
// backup system whose first step is a binary that does not exist is a backup
// system that has never run.
//
// WHAT THIS DUMPS INSTEAD, and why it is enough:
//
//   THE SCHEMA IS ALREADY IN THE REPOSITORY. This project has 139 numbered
//   migrations that run on every deploy and are idempotent by design. The
//   schema is not something to back up; it is something to re-run. Tables,
//   indexes, constraints, functions and triggers all come back by running
//   them against an empty database.
//
//   SO THE BACKUP CARRIES THE DATA, and the one thing migrations cannot
//   reproduce: WHERE EACH SEQUENCE HAD GOT TO. Restore the rows without
//   restoring the sequence positions and the next insert collides with an
//   existing primary key — the database looks fine until somebody tries to
//   add a row, and then it is broken in a way nobody connects to the restore.
//
// STREAMED IN PAGES. The instance has 512 MB. Asking node-postgres for
// "SELECT * FROM analytics_events" buffers every row in memory before the
// first one is written, which on a table of any size is how a backup becomes
// an outage. Rows are read in pages and written out as they arrive.
//
// THE OUTPUT IS PLAIN SQL, deliberately. It can be read, diffed, partially
// applied, and loaded by anything that speaks Postgres — including psql on a
// laptop, which is exactly where somebody will be when they need it.

const pool = require('../db');

// Rows per query. Small enough that one page is never large in memory, big
// enough that a table of ten thousand rows is not ten thousand round trips.
const PAGE_SIZE = 500;

// Tables that are noise in a backup: they are rebuilt by use, and including
// them can multiply the size of the dump for nothing. Each is listed with the
// reason, so the decision can be revisited rather than guessed at.
const SKIP_TABLES = new Set([
  'schema_migrations',  // rebuilt by running the migrations themselves
  'analytics_events',   // regenerated by traffic; retention already prunes it
  'page_views',         // as above
  'content_views',      // as above — the aggregate that matters is derived
]);

function quoteIdent(name) {
  return '"' + String(name).replace(/"/g, '""') + '"';
}

// A value as SQL. Everything is parameterless text, because the dump has to be
// loadable by psql with no client involved.
function quoteValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (Buffer.isBuffer(value)) return `'\\x${value.toString('hex')}'`;
  if (Array.isArray(value) || (typeof value === 'object')) {
    // Arrays and json/jsonb both come back as objects; both load correctly
    // from a quoted JSON literal with an explicit cast added by the column
    // type on the way in.
    return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Tables in an order that can actually be loaded.
//
// ALPHABETICAL ORDER DOES NOT WORK, and the tests found out the hard way:
// "competition_entries" sorts before "competitions", so the rows referencing a
// competition were inserted before the competition existed and the load failed
// on a foreign key.
//
// So the tables are sorted by their dependencies — a table is written after
// everything it points at. No special privileges are needed for this, which
// matters: disabling foreign key checks during a load requires superuser, and
// nobody has superuser on managed Postgres.
async function listTables() {
  const tables = (await pool.query(`
    SELECT c.relname AS table_name
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind = 'r'
     ORDER BY c.relname`)).rows
    .map((x) => x.table_name)
    .filter((t) => !SKIP_TABLES.has(t));

  const deps = (await pool.query(`
    SELECT DISTINCT
           src.relname AS child,
           tgt.relname AS parent
      FROM pg_constraint con
      JOIN pg_class src ON src.oid = con.conrelid
      JOIN pg_class tgt ON tgt.oid = con.confrelid
      JOIN pg_namespace n ON n.oid = src.relnamespace
     WHERE con.contype = 'f' AND n.nspname = 'public'`)).rows;

  const present = new Set(tables);
  const parentsOf = new Map(tables.map((t) => [t, new Set()]));
  for (const { child, parent } of deps) {
    // A table pointing at itself — a parent_id, say — cannot be ordered
    // around, and does not need to be: rows are written in primary key order,
    // and a child row always has a higher id than the parent it was created
    // under.
    if (child === parent) continue;
    if (present.has(child) && present.has(parent)) parentsOf.get(child).add(parent);
  }

  const ordered = [];
  const done = new Set();
  const visiting = new Set();

  function visit(table) {
    if (done.has(table)) return;
    if (visiting.has(table)) {
      // A cycle: two tables referencing each other. Rare, and unresolvable by
      // ordering alone — the load would need deferred constraints. Left where
      // it is rather than looping forever, and the load will say so plainly if
      // it ever actually fails.
      return;
    }
    visiting.add(table);
    for (const parent of parentsOf.get(table) || []) visit(parent);
    visiting.delete(table);
    done.add(table);
    ordered.push(table);
  }

  for (const table of tables) visit(table);
  return ordered;
}

async function columnsOf(table) {
  const r = await pool.query(`
    SELECT column_name FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = $1
     ORDER BY ordinal_position`, [table]);
  return r.rows.map((x) => x.column_name);
}

// The column to page by. A primary key gives stable order and lets paging use
// a WHERE rather than an OFFSET, which stays fast on a large table — OFFSET
// makes the database count past every row it has already sent.
async function pagingKeyOf(table) {
  const r = await pool.query(`
    SELECT a.attname
      FROM pg_index i
      JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
     WHERE i.indrelid = $1::regclass AND i.indisprimary
     ORDER BY a.attnum`, [`public.${quoteIdent(table)}`]);
  // Only a single-column key is usable this way; a composite one falls back
  // to OFFSET, which is correct but slower.
  return r.rowCount === 1 ? r.rows[0].attname : null;
}

// Where every sequence had got to. Restored last, because loading rows with
// explicit ids does not move a sequence along and the next insert would
// otherwise collide with a row that already exists.
async function sequencePositions() {
  const r = await pool.query(`
    SELECT sequencename AS name, last_value
      FROM pg_sequences WHERE schemaname = 'public' ORDER BY sequencename`);
  return r.rows.filter((x) => x.last_value !== null);
}

// Writes the whole dump to `write`, a function taking a string.
//
// Returns a summary: which tables, how many rows, how many bytes.
async function dumpTo(write, options = {}) {
  const started = Date.now();
  const tables = options.tables || await listTables();
  const summary = { tables: [], rows: 0, bytes: 0, sequences: 0 };

  const out = (text) => { summary.bytes += Buffer.byteLength(text); write(text); };

  out('-- Unplug Magazine — data backup\n');
  out(`-- taken ${new Date().toISOString()}\n`);
  out('--\n');
  out('-- THIS IS DATA ONLY. The schema lives in db/migrations and is rebuilt by\n');
  out('-- running them against an empty database first. See OPERATIONS.md.\n');
  out('--\n');
  out('-- THE TABLE ORDER BELOW IS DELIBERATE: each table appears after the ones\n');
  out('-- it references, so foreign keys hold at every point during the load.\n');
  out('-- Sorting this file alphabetically would break it.\n');
  out('--\n');
  out('-- Loading this over existing rows will FAIL on primary keys, and that is\n');
  out('-- deliberate. This file does not TRUNCATE anything, so it can never\n');
  out('-- silently replace a live database — running it by accident is an error,\n');
  out('-- not a disaster.\n');
  out('--\n');
  out('-- Restoring therefore means: empty database, run the migrations, empty\n');
  out('-- the tables the migrations seeded, then load this. That is what\n');
  out('-- scripts/restore-backup.js does, and why it is a script rather than a\n');
  out('-- button.\n\n');
  out('BEGIN;\n\n');

  for (const table of tables) {
    const columns = await columnsOf(table);
    if (!columns.length) continue;

    const key = await pagingKeyOf(table);
    const columnList = columns.map(quoteIdent).join(', ');
    let written = 0;
    let after = null;

    for (;;) {
      let page;
      if (key) {
        page = await pool.query(
          `SELECT * FROM ${quoteIdent(table)}
            ${after === null ? '' : `WHERE ${quoteIdent(key)} > $2`}
            ORDER BY ${quoteIdent(key)} LIMIT $1`,
          after === null ? [PAGE_SIZE] : [PAGE_SIZE, after]);
      } else {
        page = await pool.query(
          `SELECT * FROM ${quoteIdent(table)} LIMIT $1 OFFSET $2`, [PAGE_SIZE, written]);
      }
      if (page.rowCount === 0) break;

      if (written === 0) out(`-- ${table}\n`);
      for (const row of page.rows) {
        const values = columns.map((c) => quoteValue(row[c])).join(', ');
        out(`INSERT INTO ${quoteIdent(table)} (${columnList}) VALUES (${values});\n`);
      }
      written += page.rowCount;
      if (key) after = page.rows[page.rows.length - 1][key];
      if (page.rowCount < PAGE_SIZE) break;
    }

    if (written) {
      out('\n');
      summary.tables.push({ table, rows: written });
      summary.rows += written;
    }
  }

  // Sequences last. See the note above: without these the database looks
  // restored and breaks on the next insert.
  const sequences = await sequencePositions();
  if (sequences.length) {
    out('-- Sequence positions. Without these the next insert collides with a\n');
    out('-- row that already exists, and the database only looks restored.\n');
    for (const seq of sequences) {
      out(`SELECT setval('${seq.name.replace(/'/g, "''")}', ${seq.last_value}, true);\n`);
    }
    out('\n');
    summary.sequences = sequences.length;
  }

  out('COMMIT;\n');
  summary.ms = Date.now() - started;
  return summary;
}

module.exports = { dumpTo, listTables, quoteValue, quoteIdent, sequencePositions, SKIP_TABLES, PAGE_SIZE };
